import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Inter'],
                body: ['Inter'],
                label: ['Inter'],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            colors: {
                'inverse-surface': '#3d2d28',
                'on-secondary-fixed': '#3a0a00',
                'on-secondary-container': '#772e17',
                'on-surface': '#261814',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
                'surface-variant': '#f8ddd5',
                'secondary-fixed-dim': '#ffb59e',
                'surface-container-high': '#fee2db',
                'on-tertiary-fixed-variant': '#574500',
                'on-primary-container': '#ffeae5',
                'on-primary': '#ffffff',
                'on-tertiary': '#ffffff',
                'secondary-container': '#ff9879',
                'on-error-container': '#93000a',
                'inverse-primary': '#ffb59e',
                'secondary-fixed': '#ffdbd0',
                'error-container': '#ffdad6',
                'tertiary': '#735c00',
                'tertiary-container': '#c8a844',
                'on-secondary-fixed-variant': '#793018',
                'inverse-on-surface': '#ffede8',
                'primary-container': '#c53b04',
                'background': '#fff8f6',
                'on-secondary': '#ffffff',
                'secondary': '#97462d',
                'primary-fixed': '#ffdbd0',
                'outline': '#8e7068',
                'on-primary-fixed': '#3a0a00',
                'primary': '#9c2b00',
                'surface-container-lowest': '#ffffff',
                'tertiary-fixed': '#ffe087',
                'on-surface-variant': '#5a4139',
                'outline-variant': '#e2bfb5',
                'surface-bright': '#fff8f6',
                'on-tertiary-fixed': '#241a00',
                'on-primary-fixed-variant': '#852400',
                'tertiary-fixed-dim': '#e5c35c',
                'surface-tint': '#ae3200',
                'surface': '#fff8f6',
                'surface-container': '#ffe9e3',
                'primary-fixed-dim': '#ffb59e',
                'on-tertiary-container': '#4e3d00',
                'surface-container-low': '#fff1ed',
                'surface-container-highest': '#f8ddd5',
                'on-background': '#261814',
                'surface-dim': '#efd4cd',
            },
        },
    },

    plugins: [forms],
};
